[program:nexdine-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/arjun/Documents/restaurant-pos-web/restaurant-pos-api/artisan queue:work database --queue=high,default,imports,notifications,printing --sleep=2 --tries=3 --timeout=120 --max-time=3600
directory=/home/arjun/Documents/restaurant-pos-web/restaurant-pos-api
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/home/arjun/Documents/restaurant-pos-web/restaurant-pos-api/storage/logs/queue-worker.log
stopwaitsecs=130

[program:nexdine-reverb]
command=php /home/arjun/Documents/restaurant-pos-web/restaurant-pos-api/artisan reverb:start --host=127.0.0.1 --port=8080
directory=/home/arjun/Documents/restaurant-pos-web/restaurant-pos-api
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/arjun/Documents/restaurant-pos-web/restaurant-pos-api/storage/logs/reverb.log

[program:nexdine-scheduler]
command=php /home/arjun/Documents/restaurant-pos-web/restaurant-pos-api/artisan schedule:work
directory=/home/arjun/Documents/restaurant-pos-web/restaurant-pos-api
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/arjun/Documents/restaurant-pos-web/restaurant-pos-api/storage/logs/scheduler.log

[group:nexdine]
programs=nexdine-queue,nexdine-reverb,nexdine-scheduler
priority=999
