<?php

use Modules\User\Enums\PermissionAction as Action;

return [
    'monthly_sales_report' => [
        'queue' => env('MONTHLY_SALES_REPORT_QUEUE', env('QUEUE_NAME', 'default')),
        'stale_after_minutes' => env('MONTHLY_SALES_REPORT_STALE_AFTER_MINUTES', 5),
    ],

    'enterprise_summary' => [
        'queue' => env('ENTERPRISE_REPORT_SUMMARY_QUEUE', 'reports'),
    ],

    'permissions' => [
        'waiter_settlements' => [
            Action::Index,
            Action::Create,
        ],
        'reports' => [
            Action::Index,
            Action::Sales,
            Action::ProductsPurchase,
            Action::Tax,
            Action::BranchPerformance,
            Action::AggregatorPayoutReconciliation,
            Action::FinanceReconciliation,
            Action::Payments,
            Action::DiscountsAndVouchers,
            Action::ProductTax,
            Action::IngredientUsage,
            Action::StockValuation,
            Action::WastageCost,
            Action::LowStockAlerts,
            Action::RegisterSummary,
            Action::CashMovement,
            Action::SalesByCreator,
            Action::SalesByCashier,
            Action::SalesByWaiter,
            Action::WaiterCollection,
            Action::PeakHourSales,
            Action::CategorizedProducts,
            Action::UpcomingOrders,
            Action::CostAndRevenueByOrder,
            Action::CostAndRevenueByProduct,
            Action::MenuEngineering,
            Action::SlowMovingProducts,
            Action::MonthlySales,
            Action::GstDashboard,
            Action::GstSalesSummary,
            Action::GstRateWiseSales,
            Action::GstHsnSummary,
            Action::GstInvoiceRegister,
            Action::GstB2bSales,
            Action::GstB2cSales,
            Action::GstCollection,
            Action::GstGstr1Summary,
            Action::GstGstr3bSummary,
            Action::GstCreditNotes,
            Action::GstDebitNotes,
            Action::GstCancelledInvoices,
            Action::GstBranchWise,
            Action::GstOrderTypeWise,
            Action::GstPaymentMethod,
            Action::GstItemWiseSales,
            Action::GstAuditReport,
            Action::GstExceptionReport,
            Action::Downloads,
            Action::LoyaltyLastActivity,
            Action::LoyaltyInactiveCustomers,
            Action::LoyaltyNoRedemptions,
            Action::LoyaltyTopCustomersByPoints,
            Action::LoyaltyProgramSummary,
            Action::LoyaltyTotalEarnedPoints,
            Action::LoyaltyTotalRedeemedPoints,
            Action::LoyaltyTotalExpiredPoints,
            Action::LoyaltySystemPointsBalance,
            Action::LoyaltyRedemptionRate,
            Action::LoyaltyAveragePointsPerProgram,
            Action::LoyaltyPointsLifecycleTimeline,
            Action::loyaltyTierRedemptionRate,
            Action::LoyaltyTierCustomerDistribution,
            Action::LoyaltyMostRedeemedRewards,
            Action::LoyaltyLeastUsedRewards,
            Action::LoyaltyNeverRedeemedRewards,
            Action::LoyaltyRewardsByType,
            Action::LoyaltyRewardsByTier,
            Action::LoyaltyRewardsByProgram,
            Action::LoyaltyAvailableGifts,
            Action::LoyaltyUsedGifts,
            Action::LoyaltyExpiredGifts,
            Action::LoyaltyGiftUsageRate,
            Action::LoyaltyUnusedGiftsPerCustomer,
            Action::LoyaltyRedemptionsByStatus,
            Action::LoyaltyRedemptionsByProgram,
            Action::LoyaltyAveragePointsPerRedemption,
            Action::LoyaltyActivePromotions,
            Action::LoyaltyExpiredPromotions,
            Action::LoyaltyPromotionUsage,
            Action::LoyaltyHighestImpactPromotions,
            Action::LoyaltyBonusVsMultiplierComparison,
            Action::LoyaltyCategoryBoostPromotions,
            Action::LoyaltyNewMemberPromotions,
            Action::LoyaltyAverageOrderValueLoyaltyCustomers,
            Action::LoyaltyRevenueFromLoyaltyCustomers,
            Action::LoyaltyRevenueBeforeAfterLoyalty,
            Action::LoyaltyFreeItemsCost,
        ],
    ],
];
